### ISSUE TITLE
Recall curve not visible in tensorboard

### ISSUE THREAD

**Issue by amkent5** [akionakamura/pr-tensorboard-keras-example#1]
Hi!

I've applied your code to a simple binary classification (pima diabetes data set).

Strangely, in tensorboard I cannot see the recall line on the pr_curve chart. The tooltip reveals both the precision and recall values (so the callback has successfully logged the data), however the recall line is not rendering on the chart.

Have you seen this?

FYI I also had to change the tag attribute to name in the below to get this working:
self.pr_summary = pr_summary.op(
                                            #tag='pr_curve',
                                            name='pr_curve',
                                            predictions=predictions,
                                            labels=labels,
                                            display_name='Precision-Recall Curve')

Thanks -

**Comment by akionakamura** [comment]
Thanks for the warning. I've updated the code with the latest library versions. Furthermore, I've pinned them with Pipenv, so we can reproduce forever.
