### ISSUE TITLE
define a new scalars

### ISSUE THREAD

**Issue by INJNainggolan** [akionakamura/pr-tensorboard-keras-example#2]
Hello 
I have a question want to ask for you
If I define a new scalars, how can I visualize it on Tensorboard in Keras?
such as I define a new variable learning_rate, It changes over epoch, how I can visualize it on tensorboard?
I used keras, backend is tensorflow.
Looking forward to your reply.

**Comment by akionakamura** [comment]
Perhaps this link can help you: https://github.com/keras-team/keras/pull/9168#issuecomment-359901128

**Comment by akionakamura** [comment]
@INJNainggolan let me know if I can be of any further help. Closing this.
